name: rastmobile_task_enes_dorukbasi
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  # DESIGN
  cupertino_icons: ^1.0.2
  responsive_sizer: ^3.2.0
  flutter_svg: ^2.0.9
  animation_search_bar: ^0.0.10
  #STATE
  flutter_bloc: ^8.1.3
  go_router: ^12.1.1
  get: ^4.6.6
  #DATA
  sqflite: ^2.3.0
  flutter_secure_storage: ^9.0.0
  flutter_web_browser: ^0.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

